export { AIController } from './ai/controller'
export { PersonalityEngine } from './ai/personality-engine'
export { SurvivalEngine } from './ai/survival-engine'
export { AIPatterns, createInitialPatternState, type PatternState } from './ai/patterns'
export type { AIIntent, MoveProposal, VetoVerdict, ChamberDiagnosis } from './ai/types'
