/**
 * The canonical, static catalogue of all 80 achievements.
 *
 * Nothing here mutates at runtime — it is pure read-only data used by the
 * evaluator, the UI, and the backend alike.
 */

import type { AchievementDef } from './achievements-protocol'

export const ACHIEVEMENT_DEFS: readonly AchievementDef[] = [
  // ─── Pillar 1: Platform, Social & Meta ───────────────────────────────────

  // Track: Candy Vault
  {
    id: 'candy_sweet_tooth',
    pillar: 'platform',
    track: 'Candy Vault',
    name: '🍬 Sweet Tooth',
    description: 'Reach an all-time high-water mark of 10 Candies banked in your global vault.',
    icon: '🍬',
    maxProgress: 10,
  },
  {
    id: 'candy_hoarder',
    pillar: 'platform',
    track: 'Candy Vault',
    name: '🍬 Candy Hoarder',
    description: 'Reach an all-time high-water mark of 100 Candies banked in your global vault.',
    icon: '🍬',
    maxProgress: 100,
  },
  {
    id: 'candy_sugar_maniac',
    pillar: 'platform',
    track: 'Candy Vault',
    name: '🍬 Sugar Maniac',
    description: 'Reach an all-time high-water mark of 500 Candies banked in your global vault.',
    icon: '🍬',
    maxProgress: 500,
  },
  {
    id: 'candy_confectionery_tycoon',
    pillar: 'platform',
    track: 'Candy Vault',
    name: '🍬 Confectionery Tycoon',
    description: 'Reach an all-time high-water mark of 2,000 Candies banked in your global vault.',
    icon: '🍬',
    maxProgress: 2000,
  },

  // Track: Arcade Devotion
  {
    id: 'runs_first_quarter',
    pillar: 'platform',
    track: 'Arcade Devotion',
    name: '🪙 First Quarter',
    description: 'Play 5 total runs across any game in the catalogue.',
    icon: '🪙',
    maxProgress: 5,
  },
  {
    id: 'runs_arcade_regular',
    pillar: 'platform',
    track: 'Arcade Devotion',
    name: '🕹️ Arcade Regular',
    description: 'Play 50 total runs across the catalogue.',
    icon: '🕹️',
    maxProgress: 50,
  },
  {
    id: 'runs_arcade_veteran',
    pillar: 'platform',
    track: 'Arcade Devotion',
    name: '🕹️ Arcade Veteran',
    description: 'Play 200 total runs across the catalogue.',
    icon: '🕹️',
    maxProgress: 200,
  },
  {
    id: 'runs_living_legend',
    pillar: 'platform',
    track: 'Arcade Devotion',
    name: '👑 Living Legend',
    description: 'Play 800 total runs across the catalogue.',
    icon: '👑',
    maxProgress: 800,
  },

  // Track: Daily Loops & Streaks
  {
    id: 'streak_double_play',
    pillar: 'platform',
    track: 'Daily Loops & Streaks',
    name: '🔥 Double Play',
    description: 'Maintain a 2-day active play streak.',
    icon: '🔥',
    maxProgress: 2,
  },
  {
    id: 'streak_workweek_warrior',
    pillar: 'platform',
    track: 'Daily Loops & Streaks',
    name: '🔥 Workweek Warrior',
    description: 'Maintain a 5-day active play streak.',
    icon: '🔥',
    maxProgress: 5,
  },
  {
    id: 'streak_full_week_punch',
    pillar: 'platform',
    track: 'Daily Loops & Streaks',
    name: '🔥 Full Week Punch',
    description: 'Complete all 7 active days on your weekly streak punch card.',
    icon: '🔥',
    maxProgress: 7,
  },
  {
    id: 'streak_fortnight_fortitude',
    pillar: 'platform',
    track: 'Daily Loops & Streaks',
    name: '🔥 Fortnight Fortitude',
    description: 'Maintain a 14-day consecutive active play streak.',
    icon: '🔥',
    maxProgress: 14,
  },

  // Track: Identity & Customization
  {
    id: 'identity_claimed',
    pillar: 'platform',
    track: 'Identity & Customization',
    name: '🏷️ Claimed Identity',
    description: 'Auto-awarded on account creation! Welcome to Nixlabs Games.',
    icon: '🏷️',
    maxProgress: null,
  },
  {
    id: 'identity_picture_perfect',
    pillar: 'platform',
    track: 'Identity & Customization',
    name: '🖼️ Picture Perfect',
    description: 'Upload a custom profile picture to your Player Passport.',
    icon: '🖼️',
    maxProgress: null,
  },
  {
    id: 'identity_lab_pioneer',
    pillar: 'platform',
    track: 'Identity & Customization',
    name: '⚡ Lab Pioneer',
    description: '"This player was here from the start!" — awarded to early access and legacy members.',
    icon: '⚡',
    maxProgress: null,
  },
  {
    id: 'identity_developer',
    pillar: 'platform',
    track: 'Identity & Customization',
    name: '🛠️ Lab Developer',
    description: 'Develops games for our Lab.',
    icon: '🛠️',
    maxProgress: null,
  },

  // Track: Social & Competition
  {
    id: 'social_passport_stamp',
    pillar: 'platform',
    track: 'Social & Competition',
    name: '📋 Passport Stamp',
    description: 'Copy your profile link to the clipboard to share with others.',
    icon: '📋',
    maxProgress: null,
  },
  {
    id: 'social_gauntlet_thrown',
    pillar: 'platform',
    track: 'Social & Competition',
    name: '⚔️ Gauntlet Thrown',
    description: "Launch a direct Challenge Run from another player's profile card.",
    icon: '⚔️',
    maxProgress: null,
  },
  {
    id: 'social_top_bracket',
    pillar: 'platform',
    track: 'Social & Competition',
    name: '💎 Top Bracket',
    description: 'Achieve an overall Arcade Rating in the Top 3% or higher on your passport.',
    icon: '💎',
    maxProgress: null,
  },

  // Track: Exploration & Shortcuts
  {
    id: 'explore_grand_tour',
    pillar: 'platform',
    track: 'Exploration & Shortcuts',
    name: '🗺️ Grand Tour',
    description: 'Play every game in the Nixlabs catalogue at least once.',
    icon: '🗺️',
    maxProgress: null,
  },
  {
    id: 'explore_terminal_velocity',
    pillar: 'platform',
    track: 'Exploration & Shortcuts',
    name: '⌨️ Terminal Velocity',
    description: 'Use the / keyboard shortcut to instantly focus the global game search.',
    icon: '⌨️',
    maxProgress: null,
  },

  // ─── Pillar 2: Avoid the Spikes! ─────────────────────────────────────────

  // Track: Wall Bounce Milestones
  {
    id: 'avoid_wall_tapper',
    pillar: 'avoid-the-spikes',
    track: 'Wall Bounce Milestones',
    name: '🧱 Wall Tapper',
    description: 'Score 10 wall bounces in a single run in Avoid the Spikes!.',
    icon: '🧱',
    maxProgress: 10,
  },
  {
    id: 'avoid_wall_bouncer',
    pillar: 'avoid-the-spikes',
    track: 'Wall Bounce Milestones',
    name: '🧱 Wall Bouncer',
    description: 'Score 20 wall bounces in a single run in Avoid the Spikes!.',
    icon: '🧱',
    maxProgress: 20,
  },
  {
    id: 'avoid_spike_hopper',
    pillar: 'avoid-the-spikes',
    track: 'Wall Bounce Milestones',
    name: '🧱 Spike Hopper',
    description: 'Score 50 wall bounces in a single run in Avoid the Spikes!.',
    icon: '🧱',
    maxProgress: 50,
  },
  {
    id: 'avoid_century_flyer',
    pillar: 'avoid-the-spikes',
    track: 'Wall Bounce Milestones',
    name: '🧱 Century Flyer',
    description: 'Score 100 wall bounces in a single run in Avoid the Spikes!.',
    icon: '🧱',
    maxProgress: 100,
  },

  // Track: Mid-Flight Candy Collector
  {
    id: 'avoid_candy_snack',
    pillar: 'avoid-the-spikes',
    track: 'Mid-Flight Candy Collector',
    name: '💎 Snack on the Wing',
    description: 'Collect 5 Candies in a single Avoid the Spikes! run.',
    icon: '💎',
    maxProgress: 5,
  },
  {
    id: 'avoid_candy_mid_air',
    pillar: 'avoid-the-spikes',
    track: 'Mid-Flight Candy Collector',
    name: '💎 Mid-Air Glutton',
    description: 'Collect 15 Candies in a single Avoid the Spikes! run.',
    icon: '💎',
    maxProgress: 15,
  },
  {
    id: 'avoid_candy_sweet_flight',
    pillar: 'avoid-the-spikes',
    track: 'Mid-Flight Candy Collector',
    name: '💎 Sweet Flight',
    description: 'Collect 30 Candies in a single Avoid the Spikes! run.',
    icon: '💎',
    maxProgress: 30,
  },
  {
    id: 'avoid_candy_gem_swarm',
    pillar: 'avoid-the-spikes',
    track: 'Mid-Flight Candy Collector',
    name: '💎 Gem Swarm',
    description: 'Collect 500 lifetime Candies in Avoid the Spikes!.',
    icon: '💎',
    maxProgress: 500,
  },

  // Track: Floating Hazard Navigation
  {
    id: 'avoid_mover_moving_teeth',
    pillar: 'avoid-the-spikes',
    track: 'Floating Hazard Navigation',
    name: '⚠️ Moving Teeth',
    description: 'Survive past bounce 10 when floating center spikes spawn in Avoid the Spikes!.',
    icon: '⚠️',
    maxProgress: null,
  },
  {
    id: 'avoid_mover_slalom_pilot',
    pillar: 'avoid-the-spikes',
    track: 'Floating Hazard Navigation',
    name: '🎯 Slalom Pilot',
    description: 'Dodge past 10 floating spike passes in a single run in Avoid the Spikes!.',
    icon: '🎯',
    maxProgress: 10,
  },
  {
    id: 'avoid_mover_chaos_navigator',
    pillar: 'avoid-the-spikes',
    track: 'Floating Hazard Navigation',
    name: '🌪️ Chaos Navigator',
    description: 'Reach bounce 30+ amidst floating hazard crossfires in Avoid the Spikes!.',
    icon: '🌪️',
    maxProgress: null,
  },
  {
    id: 'avoid_destroy_movers_10',
    pillar: 'avoid-the-spikes',
    track: 'Floating Hazard Navigation',
    name: '💥 Red Sweeper',
    description: 'Destroy 10 red floating spikes by collecting candy in Avoid the Spikes!.',
    icon: '💥',
    maxProgress: 10,
  },
  {
    id: 'avoid_destroy_movers_50',
    pillar: 'avoid-the-spikes',
    track: 'Floating Hazard Navigation',
    name: '🧨 Hazard Obliterator',
    description: 'Destroy 50 red floating spikes by collecting candy in Avoid the Spikes!.',
    icon: '🧨',
    maxProgress: 50,
  },
  {
    id: 'avoid_destroy_movers_80',
    pillar: 'avoid-the-spikes',
    track: 'Floating Hazard Navigation',
    name: '🎆 Apex Purifier',
    description: 'Destroy 80 red floating spikes by collecting candy in Avoid the Spikes!.',
    icon: '🎆',
    maxProgress: 80,
  },

  // Track: Precision Grazes & Separating-Axis Saves
  {
    id: 'avoid_graze_razor',
    pillar: 'avoid-the-spikes',
    track: 'Precision Grazes',
    name: '🔪 Razor Graze',
    description: 'Graze a spike tip and reflect safely in Avoid the Spikes!.',
    icon: '🔪',
    maxProgress: null,
  },
  {
    id: 'avoid_graze_danger_dancer',
    pillar: 'avoid-the-spikes',
    track: 'Precision Grazes',
    name: '🔪 Danger Dancer',
    description: 'Graze 3 spike tips in a single run and survive in Avoid the Spikes!.',
    icon: '🔪',
    maxProgress: 3,
  },
  {
    id: 'avoid_graze_needle_threader',
    pillar: 'avoid-the-spikes',
    track: 'Precision Grazes',
    name: '🔪 Needle Threader',
    description: 'Graze 5 spike tips in a single run in Avoid the Spikes!.',
    icon: '🔪',
    maxProgress: 5,
  },

  // Track: Perimeter Extremities & Hazard Proximity
  {
    id: 'avoid_edge_ceiling_skimmer',
    pillar: 'avoid-the-spikes',
    track: 'Perimeter Extremities',
    name: '🦷 Ceiling Skimmer',
    description: 'Pass within 10px of the lethal ceiling teeth and land safely on a wall in Avoid the Spikes!.',
    icon: '🦷',
    maxProgress: null,
  },
  {
    id: 'avoid_edge_floor_sweeper',
    pillar: 'avoid-the-spikes',
    track: 'Perimeter Extremities',
    name: '🦷 Floor Sweeper',
    description: 'Pass within 10px of the lethal floor teeth before recovering in Avoid the Spikes!.',
    icon: '🦷',
    maxProgress: null,
  },
  {
    id: 'avoid_edge_oblivion',
    pillar: 'avoid-the-spikes',
    track: 'Perimeter Extremities',
    name: '🦷 Edge of Oblivion',
    description: 'Graze a wall spike tip within 25px of the ceiling or floor hazard band in Avoid the Spikes!.',
    icon: '🦷',
    maxProgress: null,
  },

  // Track: Flap Precision & Dynamics
  {
    id: 'avoid_flap_one_tap',
    pillar: 'avoid-the-spikes',
    track: 'Flap Precision & Dynamics',
    name: '🪶 One-Tap Transit',
    description: 'Cross the entire arena from wall to wall using exactly 1 flap in Avoid the Spikes!.',
    icon: '🪶',
    maxProgress: null,
  },
  {
    id: 'avoid_flap_quick_turnaround',
    pillar: 'avoid-the-spikes',
    track: 'Flap Precision & Dynamics',
    name: '🪶 Quick Turnaround',
    description: 'Score 2 consecutive wall bounces in under 1.8 seconds in Avoid the Spikes!.',
    icon: '🪶',
    maxProgress: null,
  },
  {
    id: 'avoid_flap_veteran_grazer',
    pillar: 'avoid-the-spikes',
    track: 'Flap Precision & Dynamics',
    name: '🪶 Veteran Grazer',
    description: 'Accumulate 25 lifetime near-miss spike tip grazes in Avoid the Spikes!.',
    icon: '🪶',
    maxProgress: 25,
  },

  // ─── Pillar 3: Pong ──────────────────────────────────────────────────────

  // Track: Rally Volleys
  {
    id: 'pong_rally_opener',
    pillar: 'pong',
    track: 'Rally Volleys',
    name: '🏓 Rally Opener',
    description: 'Maintain a 5-hit paddle rally in Pong.',
    icon: '🏓',
    maxProgress: 5,
  },
  {
    id: 'pong_paddle_ace',
    pillar: 'pong',
    track: 'Rally Volleys',
    name: '🏓 Paddle Ace',
    description: 'Maintain a 15-hit paddle rally in Pong.',
    icon: '🏓',
    maxProgress: 15,
  },
  {
    id: 'pong_kinetic_maestro',
    pillar: 'pong',
    track: 'Rally Volleys',
    name: '🏓 Kinetic Maestro',
    description: 'Maintain a 50-hit paddle rally in Pong.',
    icon: '🏓',
    maxProgress: 50,
  },
  {
    id: 'pong_infinite_volley',
    pillar: 'pong',
    track: 'Rally Volleys',
    name: '🏓 Infinite Volley',
    description: 'Maintain a 100-hit paddle rally in Pong.',
    icon: '🏓',
    maxProgress: 100,
  },

  // Track: Difficulty Progression
  {
    id: 'pong_novice_shifter',
    pillar: 'pong',
    track: 'Difficulty Progression',
    name: '🤖 Novice Shifter',
    description: 'Defeat the Easy AI in a Pong match.',
    icon: '🤖',
    maxProgress: null,
  },
  {
    id: 'pong_calculated_return',
    pillar: 'pong',
    track: 'Difficulty Progression',
    name: '🤖 Calculated Return',
    description: 'Defeat the Normal AI in a Pong match.',
    icon: '🤖',
    maxProgress: null,
  },
  {
    id: 'pong_precision_veteran',
    pillar: 'pong',
    track: 'Difficulty Progression',
    name: '🤖 Precision Veteran',
    description: 'Defeat the Hard AI in a Pong match.',
    icon: '🤖',
    maxProgress: null,
  },
  {
    id: 'pong_grandmasters_end',
    pillar: 'pong',
    track: 'Difficulty Progression',
    name: '🤖 Grandmaster\'s End',
    description: 'Defeat the Very Hard AI in a Pong match.',
    icon: '🤖',
    maxProgress: null,
  },

  // Track: The Secret Boss
  {
    id: 'pong_kinematic_anomaly',
    pillar: 'pong',
    track: 'The Secret Boss',
    name: '👁️ Kinematic Anomaly',
    description: 'Unlock the Secret Boss difficulty in Pong.',
    icon: '👁️',
    maxProgress: null,
  },
  {
    id: 'pong_algorithm_slayer',
    pillar: 'pong',
    track: 'The Secret Boss',
    name: '👁️ Algorithm Slayer',
    description: 'Defeat the predictive Secret Boss in a full Pong match.',
    icon: '👁️',
    maxProgress: null,
  },

  // Track: Shutouts & Clean Sheets
  {
    id: 'pong_solid_defense',
    pillar: 'pong',
    track: 'Shutouts & Clean Sheets',
    name: '🛡️ Solid Defense',
    description: 'Win a Pong match allowing 2 or fewer opponent points.',
    icon: '🛡️',
    maxProgress: null,
  },
  {
    id: 'pong_total_shutout',
    pillar: 'pong',
    track: 'Shutouts & Clean Sheets',
    name: '🛡️ Total Shutout',
    description: 'Win a Pong match 5-0 without allowing a single AI score.',
    icon: '🛡️',
    maxProgress: null,
  },
  {
    id: 'pong_flawless_hard',
    pillar: 'pong',
    track: 'Shutouts & Clean Sheets',
    name: '🛡️ Flawless Hard',
    description: 'Win 5-0 on Hard difficulty or higher in Pong.',
    icon: '🛡️',
    maxProgress: null,
  },

  // Track: Candy Store & Loadout
  {
    id: 'pong_loaded_paddle',
    pillar: 'pong',
    track: 'Candy Store & Loadout',
    name: '🛒 Loaded Paddle',
    description: 'Purchase and equip your first powerup using candy in Pong.',
    icon: '🛒',
    maxProgress: null,
  },
  {
    id: 'pong_tactical_triad',
    pillar: 'pong',
    track: 'Candy Store & Loadout',
    name: '🛒 Tactical Triad',
    description: 'Equip 3 different powerups in a single Pong match loadout.',
    icon: '🛒',
    maxProgress: 3,
  },
  {
    id: 'pong_full_arsenal',
    pillar: 'pong',
    track: 'Candy Store & Loadout',
    name: '🛒 Full Arsenal',
    description: 'Own all 5 Pong powerups in your inventory before spending them.',
    icon: '🛒',
    maxProgress: null,
  },
  {
    id: 'pong_max_loadout',
    pillar: 'pong',
    track: 'Candy Store & Loadout',
    name: '🛒 Max Loadout',
    description: 'Equip all 5 powerup slots and activate all 5 during a single Pong match.',
    icon: '🛒',
    maxProgress: 5,
  },

  // Track: Tactical Power Plays
  {
    id: 'pong_magnetic_trap',
    pillar: 'pong',
    track: 'Tactical Power Plays',
    name: '🧲 Magnetic Trap',
    description: 'Catch the ball with Magnet and release it with Space to score in Pong.',
    icon: '🧲',
    maxProgress: null,
  },
  {
    id: 'pong_glass_savior',
    pillar: 'pong',
    track: 'Tactical Power Plays',
    name: '🧱 Glass Savior',
    description: 'Have the Glass Wall powerup block a guaranteed AI goal in Pong.',
    icon: '🧱',
    maxProgress: null,
  },
  {
    id: 'pong_turbo_smash',
    pillar: 'pong',
    track: 'Tactical Power Plays',
    name: '⚡ Turbo Smash',
    description: 'Score a point within 1.0 second of activating Speed Boost in Pong.',
    icon: '⚡',
    maxProgress: null,
  },

  // ─── Pillar 4: FL Tron 3.0 ───────────────────────────────────────────────

  // Track: 6-Level AI Campaign
  {
    id: 'tron_grid_initiate',
    pillar: 'fl-tron-3',
    track: '6-Level AI Campaign',
    name: '🏍️ Grid Initiate',
    description: 'Defeat Stage 1: Novice in FL Tron 3.0.',
    icon: '🏍️',
    maxProgress: null,
  },
  {
    id: 'tron_vector_hunter',
    pillar: 'fl-tron-3',
    track: '6-Level AI Campaign',
    name: '🏍️ Vector Hunter',
    description: 'Defeat Stage 3: Hunter in FL Tron 3.0.',
    icon: '🏍️',
    maxProgress: null,
  },
  {
    id: 'tron_tactical_nemesis',
    pillar: 'fl-tron-3',
    track: '6-Level AI Campaign',
    name: '🏍️ Tactical Nemesis',
    description: 'Defeat Stage 5: Assassin in FL Tron 3.0.',
    icon: '🏍️',
    maxProgress: null,
  },
  {
    id: 'tron_master_core_overload',
    pillar: 'fl-tron-3',
    track: '6-Level AI Campaign',
    name: '🏍️ Master Core Overload',
    description: 'Defeat Stage 6: Master Core and complete the Campaign in FL Tron 3.0.',
    icon: '🏍️',
    maxProgress: null,
  },

  // Track: Tactical Turbo Exploits
  {
    id: 'tron_nitro_ignition',
    pillar: 'fl-tron-3',
    track: 'Tactical Turbo Exploits',
    name: '💨 Nitro Ignition',
    description: 'Activate Turbo boost with Spacebar in FL Tron 3.0.',
    icon: '💨',
    maxProgress: null,
  },
  {
    id: 'tron_turbo_cut',
    pillar: 'fl-tron-3',
    track: 'Tactical Turbo Exploits',
    name: '💨 Turbo Cut',
    description: "Overtake and cut across an AI trail while boosting in FL Tron 3.0.",
    icon: '💨',
    maxProgress: null,
  },
  {
    id: 'tron_triple_burner',
    pillar: 'fl-tron-3',
    track: 'Tactical Turbo Exploits',
    name: '💨 Triple Burner',
    description: 'Deploy all 3 Turbos in a single winning round in FL Tron 3.0.',
    icon: '💨',
    maxProgress: null,
  },
  {
    id: 'tron_pure_kinetic',
    pillar: 'fl-tron-3',
    track: 'Tactical Turbo Exploits',
    name: '💨 Pure Kinetic',
    description: 'Complete the entire 6-level FL Tron 3.0 campaign without using Turbo a single time.',
    icon: '💨',
    maxProgress: null,
  },

  // Track: The Box-In (Trapping)
  {
    id: 'tron_closed_grid',
    pillar: 'fl-tron-3',
    track: 'The Box-In',
    name: '📐 Closed Grid',
    description: 'Form a completed 4-wall light box in FL Tron 3.0.',
    icon: '📐',
    maxProgress: null,
  },
  {
    id: 'tron_iron_coil',
    pillar: 'fl-tron-3',
    track: 'The Box-In',
    name: '📐 Iron Coil',
    description: 'Spiral around an opponent AI and force an immediate trail crash in FL Tron 3.0.',
    icon: '📐',
    maxProgress: null,
  },
  {
    id: 'tron_claustrophobia',
    pillar: 'fl-tron-3',
    track: 'The Box-In',
    name: '📐 Claustrophobia',
    description: 'Trap an enemy cycle inside less than 15% of the total arena space in FL Tron 3.0.',
    icon: '📐',
    maxProgress: null,
  },

  // Track: Sweeps & Flawless Runs
  {
    id: 'tron_dominant_round',
    pillar: 'fl-tron-3',
    track: 'Sweeps & Flawless Runs',
    name: '✨ Dominant Round',
    description: 'Win a round without touching or grazing perimeter hazards in FL Tron 3.0.',
    icon: '✨',
    maxProgress: null,
  },
  {
    id: 'tron_clean_sweep',
    pillar: 'fl-tron-3',
    track: 'Sweeps & Flawless Runs',
    name: '✨ 3-0 Clean Sweep',
    description: 'Sweep an AI opponent 3 rounds to 0 in FL Tron 3.0.',
    icon: '✨',
    maxProgress: null,
  },
  {
    id: 'tron_immortal_cycle',
    pillar: 'fl-tron-3',
    track: 'Sweeps & Flawless Runs',
    name: '✨ Immortal Cycle',
    description: 'Complete the entire 6-level FL Tron 3.0 campaign without losing a single life.',
    icon: '✨',
    maxProgress: null,
  },

  // Track: Precision Cornering & Buffering
  {
    id: 'tron_hairpin_double',
    pillar: 'fl-tron-3',
    track: 'Precision Cornering & Buffering',
    name: '🕹️ Hairpin Double',
    description: 'Execute two consecutive 90° turns within 150ms in FL Tron 3.0.',
    icon: '🕹️',
    maxProgress: null,
  },
  {
    id: 'tron_razor_corridor',
    pillar: 'fl-tron-3',
    track: 'Precision Cornering & Buffering',
    name: '🕹️ Razor Corridor',
    description: 'Navigate through a narrow 1-tile light corridor with zero collision margin in FL Tron 3.0.',
    icon: '🕹️',
    maxProgress: null,
  },

  // Track: Time Trials & Blitz Clears
  {
    id: 'tron_five_second_blitz',
    pillar: 'fl-tron-3',
    track: 'Time Trials & Blitz Clears',
    name: '⚡ Five Second Blitz',
    description: 'Eliminate an enemy cycle and win a round in under 5 seconds in FL Tron 3.0.',
    icon: '⚡',
    maxProgress: null,
  },
  {
    id: 'tron_three_second_flash',
    pillar: 'fl-tron-3',
    track: 'Time Trials & Blitz Clears',
    name: '⚡ Three Second Flash',
    description: 'Eliminate an enemy cycle and win a round in under 3 seconds in FL Tron 3.0.',
    icon: '⚡',
    maxProgress: null,
  },
  {
    id: 'tron_master_speedrunner',
    pillar: 'fl-tron-3',
    track: 'Time Trials & Blitz Clears',
    name: '⚡ Master Speedrunner',
    description: 'Complete the entire 6-level FL Tron 3.0 campaign in under 3 minutes total clear time.',
    icon: '⚡',
    maxProgress: null,
  },
] as const
